# Generated by Django 2.1.2 on 2019-03-20 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskMonitor', '0003_auto_20190320_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_Task_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_date', models.DateField(verbose_name='查询时间')),
                ('economy_lowest_price', models.IntegerField(verbose_name='经济舱最低价格')),
                ('business_lowest_price', models.IntegerField(verbose_name='商务舱最低价格')),
                ('luxury_lowest_price', models.IntegerField(verbose_name='头等舱最低价格')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskMonitor.Flight_Task')),
            ],
        ),
    ]
